### ISSUE TITLE
blocks itunes from receiving keys

### ISSUE THREAD

**Issue by szymonkaliski** [julianxhokaxhiu/chrome-spotify-mediakeys-reloaded#1]
hey! the addon is great, just what I was looking for, I have just one small problem, in situation when I'm not using spotify player, but itunes, the keys stop working, would it be possible to check if spotify is opened, and if not, then propagate the keys back to the os?

**Comment by julianxhokaxhiu** [comment]
Sure! I hope to be able to provide a patch ASAP

**Comment by szymonkaliski** [comment]
:+1: thanks man!

**Comment by julianxhokaxhiu** [comment]
Well I think I have a bad news for you. I tryed to investigate the situation, and the thing is working in a totally different way.

Chrome is automatically binding to the mediakeys everytime you open it. This will be later catched as an event in my extension, which will be fired up by Chrome everytime you press a Media key.

When pressed, I'll be told which one was and I'll delegate it to spotify. So technically, if you have any Spotify tab you should no longer be able to forward actions to the spotify tab, but the play key will be anyway catched by Chrome.

You can see various blog posts or articles [talking about this](http://www.omgchrome.com/chrome-google-music-media-keys/). So I guess I've got nothing in my own hands to fix this.

Sorry :)

**Comment by szymonkaliski** [comment]
Well, that's a shame, thanks for the explanation!
